FROM registry.arna.ir/nodejs/nodejs as js-files
WORKDIR /app
RUN echo 'API_DOMAIN=""' > .env
COPY . .
RUN npm i
RUN npm run prod:site
RUN npm run prod:panel

from nginx:alpine
WORKDIR /var/www/
COPY . .
COPY --from=js-files /app/public/css /var/www/public/css
COPY --from=js-files /app/public/js /var/www/public/js
COPY docker-compose/nginx/nginx.conf /etc/nginx/conf.d/default.conf
RUN ln -s /var/www/storage/app/public /var/www/public/storage
CMD ["nginx", "-g", "daemon off;"]
