version: '2'

services:
  ehda_db:
    image: mysql:5.7
    container_name: ehda_db
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "ehda"
    networks:
      ehda-network:
        aliases:
          - ehda-mysql
    volumes:
      - 'ehda-mysqldb:/var/lib/mysql'

  nginx:
      image: nginx
      ports:
          - "80:80"
      depends_on:
        - php-fpm
      volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - '.:/var/www/'
      networks:
          - ehda-network

  php-fpm:
      build: docker-compose/php/
      volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - ./docker-compose/php/php.ini:/usr/local/etc/php/php.ini
          - ./docker-compose/php/phperror.log:/var/log/phperror.log
          - ./code:/var/www/code
          - ./docker-compose/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      networks:
          - ehda-network
      working_dir: '/var/www/code'

  composer:
      build: docker-compose/composer/
      volumes:
          - './code:/code'
          - './docker-compose/composer/cache:/root/.composer/cache'
      working_dir: /code
      networks:
          - ehda-network

  nodejs:
    build: ./docker-compose/nodejs/
    depends_on:
      - php-fpm
    volumes:
      - './code:/code'
    networks:
      - ehda-network
    working_dir: /code

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '8012:80'
    depends_on:
      - ehda_db
    restart: always
    environment:
      PMA_HOST: ehda-mysql
      PMA_ARBITRARY: 1
      PMA_USER: 'root'
      PMA_PASSWORD: 'mysql'
    networks:
      - ehda-network

  mongo-report:
    image: mongo:4.2
    ports:
      - '7071:27017'
    volumes:
      - './docker-compose/mongodb-report:/data/db'
    restart: always
    networks:
      ehda-network:
        aliases:
          - mongodb
volumes:
  ehda-mysqldb:

networks:
  ehda-network:
    driver: bridge

