apiVersion: v1
kind: Service
metadata:
  name: ehda-php-cluster-ip-service
  namespace: ehda
  labels:
    app: ehda-php
spec:
  type: ClusterIP
  selector:
    app: ehda-php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehda-php
  labels:
    app: ehda-php
spec:
  selector:
    matchLabels:
      app: ehda-php
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ehda-php
    spec:
      containers:
      - image: registry.arna.ir/ehda/ehda:TAG
        imagePullPolicy: IfNotPresent
        name: ehda-php
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "php artisan passport:install"]
        ports:
        - containerPort: 9000
          name: ehda-php
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/.env
          name: ehda-env
          subPath: .env
        - mountPath: /var/www/storage/app/public
          name: ehda-storage
        - mountPath: /var/www/public/images
          name: ehda-images
      volumes:
      - name: ehda-env
        configMap:
          name: ehda-env-config
      - name: ehda-storage
        persistentVolumeClaim:
          claimName: ehda-app-pv-claim
      - name: ehda-images
        persistentVolumeClaim:
          claimName: ehda-images-pv-claim

      imagePullSecrets:
      - name: registry
      nodeSelector:
        ehdacenter: "true"
